name: libcalendar
description: Calendar Conversion Library for Dart.
version: 0.1.0
author: Zulfahmi Ahmad <zulfahmi93@outlook.com>
homepage: https://github.com/zulfahmi93/dart_libcalendar

environment:
  sdk: '>=2.0.0-dev.54.0 <3.0.0'

dependencies:
  logging: ^0.11.3+1
  meta: ^1.1.5

dev_dependencies:
  test: ^1.3.0
